Repository ethereum/mist, pull requests merged in 2018-02, with the labels that each got.

#3421 Upgrade del to 3.0.0
  package.json
  yarn.lock
Labels: Module: Build process, Status: Please merge

#3540 Updating OS-timesync package.
  package.json
  yarn.lock
Labels: Module: Ethereum Node, Status: Please review

#3688 Updating Geth to 1.8.1 (Iceberg)
  clientBinaries.json
Labels: Status: Please review

#3451 ethereumNode Logging
  modules/ethereumNode.js
Labels: Module: Ethereum Node, Status: Please review

#3296 Upgrading electron
  .travis.yml
  README.md
  gulpTasks/building.js
  gulpfile.js
  package.json
  tests/.gitignore
  tests/_base.js
  yarn.lock
Labels: Module: Electron, Status: Please review
