Repository ethereum/mist, pull requests merged in 2018-03, with the labels that each got.

#3723 Adding unit tests to Travis job
  .travis.yml
Labels: Module: Build process, Status: Please review

#3715 Light mode as default setting
  modules/ethereumNode.js
Labels: Module: Ethereum Node, Status: Please review

#3729 Updates Geth to "Frost"
  clientBinaries.json
Labels: Module: Ethereum Node, Status: Please review

#3697 Removes onboarding
  interface/client/appStart.js
  interface/client/styles/importAccount.import.less
  interface/client/styles/styles.less
  interface/client/templates/popupWindows/importAccount.html
  interface/client/templates/popupWindows/importAccount.js
  interface/client/templates/popupWindows/onboardingScreen.html
  interface/client/templates/popupWindows/onboardingScreen.js
  main.js
  modules/ipcCommunicator.js
  modules/windows.js
  tests/unit/core/ui/reducer.test.js
  yarn.lock
Labels: Status: Please review

#3691 Removes popup code
  interface/.meteor/versions
  interface/i18n/mist.ca.i18n.json
  interface/i18n/mist.de.i18n.json
  interface/i18n/mist.en.i18n.json
  interface/i18n/mist.es.i18n.json
  interface/i18n/mist.fa.i18n.json
  interface/i18n/mist.fr.i18n.json
  interface/i18n/mist.it.i18n.json
  interface/i18n/mist.ja.i18n.json
  interface/i18n/mist.ko.i18n.json
  interface/i18n/mist.kr.i18n.json
  interface/i18n/mist.nb.i18n.json
  interface/i18n/mist.nl.i18n.json
  interface/i18n/mist.pt.i18n.json
  interface/i18n/mist.ru.i18n.json
  interface/i18n/mist.sq.i18n.json
  interface/i18n/mist.zh-TW.i18n.json
  interface/i18n/mist.zh.i18n.json
  modules/preloader/include/openExternal.js
  modules/preloader/include/openPopup.js
  modules/preloader/popupWindows.js
Labels: Status: Please merge

#3734 Bump electron to 1.8.3
  package.json
  yarn.lock
Labels: Module: Electron

#3763 Update electron 1.8.4
  .travis.yml
  README.md
  package.json
  yarn.lock
Labels: Status: Please review

#3766 Refactoring upload-queue task; Prettier code style changes
  .travis.yml
  gulpfile.js
Labels: Status: In progress

#3769 Update README.md with `yarn dev:meteor` shortcut
  README.md
Labels: Status: Please merge

#2980 Greenkeeper/initial
  .travis.yml
  README.md
  package.json
Labels: Status: On hold
