Repository ethereum/mist, pull requests merged in 2018-04, with the labels that each got.

#3790 cleanup: onboarding -> importAccount and translation updates
  interface/client/styles/importAccount.import.less
  interface/client/styles/networkIndicator.import.less
  interface/client/templates/popupWindows/importAccount.html
  interface/client/templates/popupWindows/importAccount.js
  interface/client/templates/popupWindows/requestAccount.html
  interface/i18n/mist.ca.i18n.json
  interface/i18n/mist.de.i18n.json
  interface/i18n/mist.en.i18n.json
  interface/i18n/mist.es.i18n.json
  interface/i18n/mist.fa.i18n.json
  interface/i18n/mist.fr.i18n.json
  interface/i18n/mist.it.i18n.json
  interface/i18n/mist.ja.i18n.json
  interface/i18n/mist.ko.i18n.json
  interface/i18n/mist.kr.i18n.json
  interface/i18n/mist.nb.i18n.json
  interface/i18n/mist.nl.i18n.json
  interface/i18n/mist.pt.i18n.json
  interface/i18n/mist.ru.i18n.json
  interface/i18n/mist.sq.i18n.json
  interface/i18n/mist.zh-TW.i18n.json
  interface/i18n/mist.zh.i18n.json
  interface/public/images/importaccount-logo-metal.png
Labels: Type: Refactor

#3774 Remove getTransactionReceipt override
  modules/ipc/methods/eth_getTransactionReceipt.js
Labels: Module: Web3, Status: Please review, Type: Refactor

#3776 Upgrade Mist to web3 1.0
  interface/.meteor/.finished-upgraders
  interface/.meteor/packages
  interface/.meteor/release
  interface/.meteor/versions
  interface/client/lib/ethereum/1_web3js_init.js
  interface/client/templates/elements/nodeInfo.js
  interface/client/templates/popupWindows/importAccount.js
  interface/client/templates/popupWindows/requestAccount.js
  interface/client/templates/popupWindows/sendTransactionConfirmation.js
  interface/client/templates/popupWindows/splashScreen.js
  interface/package-lock.json
  interface/package.json
  interface/yarn.lock
  modules/ipc/ipcProviderWrapper.js
  modules/ipc/methods/eth_accounts.js
  modules/preloader/mistUI.js
  modules/preloader/popupWindows.js
  modules/preloader/walletMain.js
  modules/swarmNode.js
  modules/web3Admin.js
  package.json
  tests/mocha-in-browser/spec/permissions-spec.js
  yarn.lock
Labels: Module: Web3, Status: Please review, Type: Enhancement
